### PR TITLE
Fix for ACC model - eliminate vehicle length from spacing margin

### PR DESCRIPTION
**Pull request by robertalms**
see #13681

### CODE REVIEW

**Comment by behrisch** [comment]
I suppose this is referring to equation 5 in https://pure.tudelft.nl/ws/portalfiles/portal/51734038/1_s2.0_S0968090X1830528X_main.pdf. You are right the L is superfluous and should not be in the code. But I have two questions: Why did you remove the "- 5". And do you have any idea what to do about the minGap here? I did not read the paper completely. Do they assume that such a concept exists or is it just part of the vehicle length?

**Comment by robertalms** [comment]
1. Sorry, removing the ' - 5' from the equation was a mistake on my side. Thanks for double checking!
2. No, I don't think they account for a safe minimum distance as `minGap`. Neither in the original publication nor in this one is anything mentioned about something like this. So, I think it's indeed bumper to bumper distances. I guess, this is why they added this spacing margin later on.

**Comment by behrisch** [comment]
But the original reporter of #13681 tried to account for the minGap so I thought it would be fair to do so as well. gap2pred in the current code does not include the minGap so it is not bumper to bumper. But you are probably right If we allow the model to violate the minGap this is a sure way to more collisions because sumo already reports minGap violations as such

**Comment by robertalms** [comment]
please also reopen #4551

**Pull request merged**
