### PR TITLE
net2geojson added extra features

### PR DESCRIPTION
**Pull request by aminissn**
related to https://github.com/eclipse-sumo/sumo/issues/15109

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks a lot for trying again! I can confirm that there is a signed ECA for the gmail address. I don't know why the github check is not picking it up correctly. (It would still fail because the commits with the other address are still present). I'll open an issue with Eclipse

**Comment by behrisch** [comment]
see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4780

**Comment by aminissn** [comment]
ah! yes, that makes totally sense, I forgot the old commits when I created a new pull request. Hopefully, this won't happen next time. Thanks for the help.

**Comment by aminissn** [comment]
@behrisch This happened again in my new pull request, this time I am only using one email in all commits! I followed the discussion on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4780 but it seems to be still an issue, right?

**Pull request merged**
