### PR TITLE
compute penalty for rejecting requests

### PR DESCRIPTION
**Pull request by ritzerp**
- previously the penalty had a default value of 10000
- now the penalty depends on the dimension of the network (diameter of bounding box)  and a penalty_factor
- penalty = penalty_factor * dimension_of_network
- the penalty factor can be modified by user input
- if cost type is time, a default speed is assumed to get equivalent dimensions

### CODE REVIEW

**Comment by behrisch** [comment]
@ritzerp Thank you! Can you add a test? Maybe in a separate PR?

**Comment by behrisch** [comment]
@rummel123 Can you have a look?

**Comment by rummel123** [comment]
> @rummel123 Can you have a look?

Yes

**Comment by ritzerp** [comment]
> @ritzerp Thank you! Can you add a test? Maybe in a separate PR?

Yes, good idea. I will try to add a test in a separate PR in the next weeks.

**Comment by rummel123** [comment]
Looks good, can be merged.

**Comment by behrisch** [comment]
@ritzerp There are several purely cosmetic changes. Could you revert them so that we can focus on the content?

**Comment by ritzerp** [comment]
@behrisch I reverted the cosmetic changes. Sorry for the late reply!

**Comment by ritzerp** [comment]
I think I found a small bug with my PR and will solve it... Please wait for the push.

**Comment by ritzerp** [comment]
@behrisch solved the problem now. The penalty has to be an integer.

**Comment by behrisch** [comment]
Thanks a lot! I still see some places where whitespace gets added at the end of a line. Can you try to remove them?

**Comment by behrisch** [comment]
Thanks a lot!

**Pull request merged**
