### PR TITLE
Implemented getIntervalVehicleNumber in InductionLoopScope for the Traci-API on the client-side

### PR DESCRIPTION
**Pull request by Enough7**
Hey,

I needed this for Artery and I would like to share this with you.
I am not familiar with your test-setup so I did only a little testing by hand.

### CODE REVIEW

**Comment by behrisch** [comment]
Thanks for the PR! The old TraCIAPI is officially deprecated so I am a little hesitant to modify it at all. Is there any reason for not using libtraci? Also why did you add another constant to TraCIConstants.h? There is already VAR_LAST_INTERVAL_NUMBER.

**Comment by Enough7** [comment]
Hi @behrisch,
thanks for the feedback.

> The old TraCIAPI is officially deprecated 

I did not know that, is there a new Traci-API or is it libtraci?

> Is there any reason for not using libtraci?

I guess [Artery](http://artery.v2x-research.eu/) does not use it?

> Also why did you add another constant to TraCIConstants.h? There is already VAR_LAST_INTERVAL_NUMBER.

I did not notice.

**Comment by behrisch** [comment]
@Enough7 Could you still do the "paperwork" (make an eclipse account and agree to the ECA), see https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work?

**Comment by Enough7** [comment]
@behrisch I use an E-Mail-Mask given by Github, which I can not use to receive E-Mails afaik. So I guess the CICD-Script would not recognize my commit's E-Mail-Address anyway. I can assure you that me and my commits apply to the ECA found [here](https://www.eclipse.org/legal/ECA.php). I may sign something with my SSH-Key I use for GitHub.

**Pull request merged**
