### PR TITLE
net2geojson update

### PR DESCRIPTION
**Pull request by aminissn**
I already had what Robert asked for in https://github.com/eclipse-sumo/sumo/issues/15109 so I thought I make the pull request

### CODE REVIEW

**Comment by namdre** [comment]
Thanks! Can you check whether your github account has ticked the appropriate ECA checkboxes in your eclipse account? (https://sumo.dlr.de/docs/FAQ.html#how_do_code_contributions_work)

**Comment by aminissn** [comment]
I don't know how to fix the Eclipse account issue, I will try again later :-/

**Comment by behrisch** [comment]
@aminissn Please make sure that your github account uses the same email address as your eclipse account and that this is also the same address as mentioned in the commit. If nothing works out, I would be also fine if you confirm here that you agree with [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).

**Comment by aminissn** [comment]
I re-executed the ESA agreement in my Eclipse account and changed my primary Email but I think the test still fails.

**Comment by aminissn** [comment]
I make a new pull request, Eclipse is always checking my deleted Email address as well for the ECA

**Pull request closed without merging**
