### PR TITLE
Path to Userdoc not found

### PR DESCRIPTION
**Pull request by Enough7**
Hi,
I could not found said path but I think the path given by the commit is the correct path

### CODE REVIEW

**Comment by m-kro** [comment]
Actually the current path should be correct, as you can check easily by downloading a release from our [downloads section](https://sumo.dlr.de/docs/Downloads.php), e.g. [v.1.18.0 for Windows](https://sumo.dlr.de/releases/1.18.0/sumo-win64-1.18.0.zip). Once unzipped, it contains subfolder docs/userdoc/ where all HTML doc pages as they were at release time are available.

**Comment by Enough7** [comment]
Why does a local build not include those docs?
I think it would be nice if every build would be on the same page.
The same goes for doxygen,
I only could find the 'daily-version' of the doxygen docs [here](https://sumo.dlr.de/daily/doxygen/) but I am interested in my 'local-version' and perhaps in older versions of the doxygen docs.
Where can I find them?

**Comment by m-kro** [comment]
You can generate both on your system, see [documentation build](https://sumo.dlr.de/docs/Developer/Documentation_Build.html) and [Doxygen website](https://www.doxygen.nl/) (the doxygen config sumo.doxyconf is included on root level of the SUMO repository).

**Comment by Enough7** [comment]
@m-kro Thank you for clarification

**Pull request closed without merging**
